### ISSUE TITLE
Add The Feature of Face Detection, Trained Model

### ISSUE THREAD

**Issue by FitnessApplication-PJT** [omkar-21bce1023/Fitness-Application-Project-Team#1]

**Comment by Omkar17Coder** [comment]
Please Allot this Issue to me. 
I have Build a Model Based on media pipe and trained it using sklearn.

**Comment by FitnessApplication-PJT** [comment]
> Please Allot this Issue to me. I have Build a Model Based on media pipe and trained it using sklearn.

`Ok
